// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "launcher.hpp"
#include <stdio.h>
#include <string>
#ifndef _WIN32
#include <unistd.h>
#include <pwd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#endif

void CinnabarLauncher::cb_play_button_i(Fl_Button*, void*) {
  save();
// TODO!
exit(EXIT_SUCCESS);
}
void CinnabarLauncher::cb_play_button(Fl_Button* o, void* v) {
  ((CinnabarLauncher*)(o->parent()))->cb_play_button_i(o,v);
}

void CinnabarLauncher::cb_options_button_i(Fl_Button* o, void*) {
  wiz->value(options_group);
o->deactivate();
play_button->deactivate();
}
void CinnabarLauncher::cb_options_button(Fl_Button* o, void* v) {
  ((CinnabarLauncher*)(o->parent()))->cb_options_button_i(o,v);
}

void CinnabarLauncher::cb_Exit_i(Fl_Button*, void*) {
  save();
exit(EXIT_SUCCESS);
}
void CinnabarLauncher::cb_Exit(Fl_Button* o, void* v) {
  ((CinnabarLauncher*)(o->parent()))->cb_Exit_i(o,v);
}

void CinnabarLauncher::cb_Save_i(Fl_Button*, void*) {
  save();
wiz->value(logo_group);
options_button->activate();
play_button->activate();
}
void CinnabarLauncher::cb_Save(Fl_Button* o, void* v) {
  ((CinnabarLauncher*)(o->parent()->parent()->parent()))->cb_Save_i(o,v);
}
CinnabarLauncher::CinnabarLauncher(int X, int Y, int W, int H, const char *L)
  : Fl_Window(X, Y, W, H, L) {
  _CinnabarLauncher();
}

CinnabarLauncher::CinnabarLauncher(int W, int H, const char *L)
  : Fl_Window(0, 0, W, H, L) {
  clear_flag(16);
  _CinnabarLauncher();
}

CinnabarLauncher::CinnabarLauncher()
  : Fl_Window(0, 0, 600, 200, "Cinnabar Engine") {
  clear_flag(16);
  _CinnabarLauncher();
}

void CinnabarLauncher::_CinnabarLauncher() {
this->box(FL_FLAT_BOX);
this->color(FL_GRAY0);
this->selection_color(FL_DARK_RED);
this->labeltype(FL_NO_LABEL);
this->labelfont(0);
this->labelsize(14);
this->labelcolor(FL_FOREGROUND_COLOR);
this->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
this->when(FL_WHEN_RELEASE);
{ play_button = new Fl_Button(520, 10, 70, 20, "Play");
  play_button->box(FL_THIN_UP_BOX);
  play_button->color((Fl_Color)64);
  play_button->selection_color(FL_DARK_RED);
  play_button->labelfont(13);
  play_button->labelcolor((Fl_Color)28);
  play_button->callback((Fl_Callback*)cb_play_button);
} // Fl_Button* play_button
{ options_button = new Fl_Button(520, 35, 70, 20, "Options");
  options_button->box(FL_THIN_UP_BOX);
  options_button->color((Fl_Color)64);
  options_button->selection_color(FL_DARK_RED);
  options_button->labelfont(13);
  options_button->labelcolor((Fl_Color)28);
  options_button->callback((Fl_Callback*)cb_options_button);
} // Fl_Button* options_button
{ Fl_Button* o = new Fl_Button(520, 60, 70, 20, "Exit");
  o->box(FL_THIN_UP_BOX);
  o->color((Fl_Color)64);
  o->selection_color(FL_DARK_RED);
  o->labelfont(13);
  o->labelcolor((Fl_Color)28);
  o->callback((Fl_Callback*)cb_Exit);
} // Fl_Button* o
{ wiz = new Fl_Wizard(0, 0, 510, 200);
  wiz->box(FL_FLAT_BOX);
  wiz->color(FL_FOREGROUND_COLOR);
  { logo_group = new Fl_Group(0, 0, 510, 200);
    logo_group->color(FL_FOREGROUND_COLOR);
    { Fl_Box* o = new Fl_Box(5, 8, 355, 92, "Cinnabar");
      o->color(FL_FOREGROUND_COLOR);
      o->labelfont(14);
      o->labelsize(63);
      o->labelcolor((Fl_Color)64);
    } // Fl_Box* o
    logo_group->end();
  } // Fl_Group* logo_group
  { options_group = new Fl_Group(0, 0, 510, 200);
    options_group->box(FL_FLAT_BOX);
    options_group->color(FL_FOREGROUND_COLOR);
    options_group->hide();
    { en_fltk = new Fl_Round_Button(10, 15, 125, 20, "FLTK OpenGL");
      en_fltk->type(102);
      en_fltk->down_box(FL_ROUND_DOWN_BOX);
      en_fltk->value(1);
      en_fltk->color(FL_BLACK);
      en_fltk->labelfont(14);
      en_fltk->labelcolor(FL_DARK_RED);
    } // Fl_Round_Button* en_fltk
    { en_glow = new Fl_Round_Button(10, 50, 125, 20, "Glow OpenGL");
      en_glow->type(102);
      en_glow->down_box(FL_ROUND_DOWN_BOX);
      en_glow->color(FL_BLACK);
      en_glow->labelfont(14);
      en_glow->labelcolor(FL_DARK_RED);
    } // Fl_Round_Button* en_glow
    { en_gl4 = new Fl_Check_Button(10, 85, 125, 20, "Use OpenGL 4");
      en_gl4->down_box(FL_DOWN_BOX);
      en_gl4->labelfont(14);
      en_gl4->labelcolor(FL_DARK_RED);
      en_gl4->deactivate();
    } // Fl_Check_Button* en_gl4
    { en_windowed = new Fl_Check_Button(10, 120, 125, 20, "Windowed");
      en_windowed->down_box(FL_DOWN_BOX);
      en_windowed->value(1);
      en_windowed->labelfont(14);
      en_windowed->labelcolor(FL_DARK_RED);
    } // Fl_Check_Button* en_windowed
    { win_w = new Fl_Int_Input(195, 12, 90, 23, "W");
      win_w->type(2);
      win_w->color((Fl_Color)64);
      win_w->selection_color((Fl_Color)48);
      win_w->labelfont(14);
      win_w->labelcolor(FL_DARK_RED);
      win_w->textfont(13);
      win_w->textcolor((Fl_Color)28);
    } // Fl_Int_Input* win_w
    { win_h = new Fl_Int_Input(305, 12, 90, 23, "H");
      win_h->type(2);
      win_h->color((Fl_Color)64);
      win_h->selection_color((Fl_Color)48);
      win_h->labelfont(14);
      win_h->labelcolor(FL_DARK_RED);
      win_h->textfont(13);
      win_h->textcolor((Fl_Color)28);
    } // Fl_Int_Input* win_h
    { Fl_Button* o = new Fl_Button(195, 50, 90, 20, "Default");
      o->box(FL_THIN_UP_BOX);
      o->color((Fl_Color)64);
      o->selection_color(FL_DARK_RED);
      o->labelfont(13);
      o->labelcolor((Fl_Color)28);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(305, 50, 20, 20, "+");
      o->box(FL_THIN_UP_BOX);
      o->color((Fl_Color)64);
      o->selection_color(FL_DARK_RED);
      o->labelfont(13);
      o->labelcolor((Fl_Color)28);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(330, 50, 20, 20, "-");
      o->box(FL_THIN_UP_BOX);
      o->color((Fl_Color)64);
      o->selection_color(FL_DARK_RED);
      o->labelfont(13);
      o->labelcolor((Fl_Color)28);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(355, 50, 40, 20, "Wide");
      o->box(FL_THIN_UP_BOX);
      o->color((Fl_Color)64);
      o->selection_color(FL_DARK_RED);
      o->labelfont(13);
      o->labelcolor((Fl_Color)28);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(325, 120, 70, 20, "Save");
      o->box(FL_THIN_UP_BOX);
      o->color((Fl_Color)64);
      o->labelfont(14);
      o->labelcolor((Fl_Color)28);
      o->callback((Fl_Callback*)cb_Save);
    } // Fl_Button* o
    options_group->end();
  } // Fl_Group* options_group
  wiz->end();
} // Fl_Wizard* wiz
clear_border();
end();
}

/**
 Saves current options.
*/
void CinnabarLauncher::save() {
  #ifdef _WIN32
  HANDLE file__;
  #define BUFFER_SIZE__ 0x400
  {
  	TCHAR *const filename__ = TEXT("cinnabar.ini");
  	const unsigned short filename_len__ = _tcslen(filename__);
  	TCHAR buffer__[BUFFER_SIZE];
  	GetModuleFileName(NULL, buffer__, BUFFER_SIZE - filename_len__);
  
  	{
  		short last_slash = -1;
  		const TCHAR slash = (TEXT("/"))[0];
  		unsigned short i;
  		for(; i < BUFFER_SIZE && buffer__[i] != 0; i++){
  			if(buffer__[i] == slash)
  				last_slash = i;
  		}
  
  		if(last_slash != -1)
  			i = last_slash;
  		unsigned short n = 0;
  		for(unsigned short n = 0; n <= filename_len__; n++){
  			buffer__[i+n] = filename__[n];
  		}
  	}
  		
  	file__ = CreateFile(buffer, FILE_SHARE_WRITE, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL);
  }
  #define CIN_WRITE(DATA, LEN) WriteFile(file__, DATA, LEN, NULL, NULL)
  #undef BUFFER_SIZE__
  #else
  int file__;
  {
  	const char *home_dir__ = getenv("HOME");
  	if(home_dir__ == NULL){
  		const struct passwd *const pw__ = getpwuid(getuid());
  		home_dir__ = pw__->pw_dir;
  	}
  	std::string path = home_dir__;
  	if(path.back() != '/')
  		path += '/';
  	path += ".cinnabar/";
  	mkdir(path.c_str(), 0777);
  	path += "cinnabar.ini";
  	file__ = open(path.c_str(), O_WRONLY|O_CREAT, S_IRUSR|S_IWUSR);
  }
  #define CIN_WRITE(DATA, LEN) (void)write(file__, DATA, LEN)
  #endif
  #define CIN_WRITE_STR(STR) CIN_WRITE(STR, sizeof(STR)-1)
  #define CIN_WRITE_STRLEN(STR) do{ const char *const STR_ = STR; CIN_WRITE(STR_, strlen(STR_)); } while(false)
  
  if(en_fltk->value())
  	CIN_WRITE_STR("window=fltk\n");
  else
  	CIN_WRITE_STR("window=glow\n");
  
  if(en_gl4->value())
  	CIN_WRITE_STR("opengl=gl4\n");
  else
  	CIN_WRITE_STR("opengl=gl2\n");
  
  if(en_windowed->value())
  	CIN_WRITE_STR("windowed=true\n");
  else
  	CIN_WRITE_STR("windowed=false\n");
  
  CIN_WRITE_STR("width=");
  CIN_WRITE_STRLEN(win_w->value());
  CIN_WRITE("\n", 1);
  
  CIN_WRITE_STR("height=");
  CIN_WRITE_STRLEN(win_h->value());
  CIN_WRITE("\n", 1);
  
  #ifdef _WIN32
  CloseHandle(file__);
  #else
  close(file__);
  #endif
}

int main(int argc, char **argv) {
  CinnabarLauncher launcher;
  launcher.show();
  launcher.wiz->value(launcher.logo_group);
  return Fl::run();
}
