:- module cell.
% AUTOGENERATED, DO NOT EDIT
% Created by libbottle generate.py, 2017-04-22
:- interface.

:- import_module buffer.

:- use_module io.

:- type lib ---> lib(string).

:- type heightmap ---> heightmap(string).

:- type header ---> header(int, int, cell_type, int, int, int, int).

:- type cell_type ---> 
    exterior ;
    interior.

:- type trigger ---> trigger(string).

:- type static ---> static(position, string, float, float, float).

:- type position ---> position(float, float, float).


:- pred examine_lib(string, lib).
:- mode examine_lib(in,out) is det.
:- mode examine_lib(out,in) is det.
:- pred write_lib(lib::in, io.io::di, io.io::uo) is det.

% read_lib(Buffer, !ByteIndex, Result).
:- pred read_lib(buffer::in, int::in, int::out, lib::out) is semidet.

:- pred examine_heightmap(string, heightmap).
:- mode examine_heightmap(in,out) is det.
:- mode examine_heightmap(out,in) is det.
:- pred write_heightmap(heightmap::in, io.io::di, io.io::uo) is det.

% read_heightmap(Buffer, !ByteIndex, Result).
:- pred read_heightmap(buffer::in, int::in, int::out, heightmap::out) is semidet.

:- pred examine_header(int, int, cell_type, int, int, int, int, header).
:- mode examine_header(in,in,in,in,in,in,in,out) is det.
:- mode examine_header(out,out,out,out,out,out,out,in) is det.
:- pred write_header(header::in, io.io::di, io.io::uo) is det.

% read_header(Buffer, !ByteIndex, Result).
:- pred read_header(buffer::in, int::in, int::out, header::out) is semidet.

:- pred examine_trigger(string, trigger).
:- mode examine_trigger(in,out) is det.
:- mode examine_trigger(out,in) is det.
:- pred write_trigger(trigger::in, io.io::di, io.io::uo) is det.

% read_trigger(Buffer, !ByteIndex, Result).
:- pred read_trigger(buffer::in, int::in, int::out, trigger::out) is semidet.

:- pred examine_static(position, string, float, float, float, static).
:- mode examine_static(in,in,in,in,in,out) is det.
:- mode examine_static(out,out,out,out,out,in) is det.
:- pred write_static(static::in, io.io::di, io.io::uo) is det.

% read_static(Buffer, !ByteIndex, Result).
:- pred read_static(buffer::in, int::in, int::out, static::out) is semidet.

:- pred examine_position(float, float, float, position).
:- mode examine_position(in,in,in,out) is det.
:- mode examine_position(out,out,out,in) is det.
:- pred write_position(position::in, io.io::di, io.io::uo) is det.

% read_position(Buffer, !ByteIndex, Result).
:- pred read_position(buffer::in, int::in, int::out, position::out) is semidet.



:- implementation.

:- import_module int.
:- use_module string.
:- use_module list.
:- use_module char.


:- pred write_string(string::in, int::in, int::in, io.io::di, io.io::uo) is det.
write_string(Str, I, N, !IO) :-
    ( I = N ->
        true
    ;
        string.det_index(Str, I, Ch),
        char.to_int(Ch, CodePoint),
        io.write_byte(CodePoint, !IO),
        write_string(Str, I + 1, N, !IO)
    ).
:- pred float_to_bytes(float::in, int::out, int::out, int::out, int::out) is det.
:- pred bytes_to_float(float::out, int::in, int::in, int::in, int::in) is det.
:- pred int_to_bytes(int::in, int::out, int::out, int::out, int::out) is det.
:- pred bytes_to_int(int::out, int::in, int::in, int::in, int::in) is det.
:- pragma foreign_proc("C", float_to_bytes(In::in, O0::out, O1::out, O2::out, O3::out),
    [promise_pure, thread_safe, does_not_affect_liveness, will_not_call_mercury, will_not_throw_exception],
    "const float f=In;const unsigned char *const uc=(unsigned char*)&f;
    O0=uc[0];O1=uc[1];O2=uc[2];O3=uc[3];    ").
:- pragma foreign_proc("C", bytes_to_float(Out::out, I0::in, I1::in, I2::in, I3::in),
    [promise_pure, thread_safe, does_not_affect_liveness, will_not_call_mercury, will_not_throw_exception],
    "float f;unsigned char *const uc=(unsigned char*)&f;
    uc[0]=I0;uc[1]=I1;uc[2]=I2;uc[3]=I3;    Out = f;
    ").
:- pragma foreign_proc("C", int_to_bytes(In::in, O0::out, O1::out, O2::out, O3::out),
    [promise_pure, thread_safe, does_not_affect_liveness, will_not_call_mercury, will_not_throw_exception],
    "const int i=In;const unsigned char *const uc=(unsigned char*)&i;
    O0=uc[0];O1=uc[1];O2=uc[2];O3=uc[3];    ").
:- pragma foreign_proc("C", bytes_to_int(Out::out, I0::in, I1::in, I2::in, I3::in),
    [promise_pure, thread_safe, does_not_affect_liveness, will_not_call_mercury, will_not_throw_exception],
    "int i;unsigned char *const uc=(unsigned char*)&i;
    uc[0]=I0;uc[1]=I1;uc[2]=I2;uc[3]=I3;    Out = i;
    ").

examine_lib(String0, lib(String0)).

:- pragma foreign_export("C", examine_lib(in,out), "Cell_CreateLib").

:- pragma foreign_export("C", examine_lib(out,in), "Cell_GetLib").

examine_heightmap(String0, heightmap(String0)).

:- pragma foreign_export("C", examine_heightmap(in,out), "Cell_CreateHeightmap").

:- pragma foreign_export("C", examine_heightmap(out,in), "Cell_GetHeightmap").

examine_header(Int0, Int1, CellType2, Int3, Int4, Int5, Int6, header(Int0, Int1, CellType2, Int3, Int4, Int5, Int6)).

:- pragma foreign_export("C", examine_header(in,in,in,in,in,in,in,out), "Cell_CreateHeader").

:- pragma foreign_export("C", examine_header(out,out,out,out,out,out,out,in), "Cell_GetHeader").

:- pragma foreign_decl("C",
    "enum EnumCellTypeType{
    eExterior,
    eInterior
};").

:- pragma foreign_enum("C",cell_type/0,[
    exterior - "eExterior",
    interior - "eInterior"]).

examine_trigger(String0, trigger(String0)).

:- pragma foreign_export("C", examine_trigger(in,out), "Cell_CreateTrigger").

:- pragma foreign_export("C", examine_trigger(out,in), "Cell_GetTrigger").

examine_static(Position0, String1, Float2, Float3, Float4, static(Position0, String1, Float2, Float3, Float4)).

:- pragma foreign_export("C", examine_static(in,in,in,in,in,out), "Cell_CreateStatic").

:- pragma foreign_export("C", examine_static(out,out,out,out,out,in), "Cell_GetStatic").

examine_position(Float0, Float1, Float2, position(Float0, Float1, Float2)).

:- pragma foreign_export("C", examine_position(in,in,in,out), "Cell_CreatePosition").

:- pragma foreign_export("C", examine_position(out,out,out,in), "Cell_GetPosition").


read_lib(Buffer, I0, IOut, Out) :- 
    get_8(Buffer, I0, TextSizeI0),
    get_ascii_string(Buffer, I0+1, TextSizeI0, File),
    I1 - 1 = TextSizeI0 + I0,
    IOut = I1,
    Out = lib(File).

write_lib(lib(File), !IO) :-
    string.length(File) = 0+LenFile,
    io.write_byte(LenFile, !IO),
    write_string(File, 0, LenFile, !IO),
    true.

read_heightmap(Buffer, I0, IOut, Out) :- 
    get_8(Buffer, I0, TextSizeI0),
    get_ascii_string(Buffer, I0+1, TextSizeI0, File),
    I1 - 1 = TextSizeI0 + I0,
    IOut = I1,
    Out = heightmap(File).

write_heightmap(heightmap(File), !IO) :-
    string.length(File) = 0+LenFile,
    io.write_byte(LenFile, !IO),
    write_string(File, 0, LenFile, !IO),
    true.

read_header(Buffer, I0, IOut, Out) :- 
    get_byte_32(Buffer, I0, CellPositionX),
    I1 - 4 = I0,
    get_byte_32(Buffer, I1, CellPositionY),
    I2 - 4 = I1,
    get_byte_8(Buffer, I2, IntI2),
    (
        IntI2 = 0,
        CellType = interior
    ;
        IntI2 = 1,
        CellType = exterior
    ),
    I3 - 1 = I2,
    get_byte_32(Buffer, I3, NumClibs),
    I4 - 4 = I3,
    get_byte_32(Buffer, I4, NumIlibs),
    I5 - 4 = I4,
    get_byte_32(Buffer, I5, NumStatics),
    I6 - 4 = I5,
    get_byte_32(Buffer, I6, NumTriggers),
    I7 - 4 = I6,
    IOut = I7,
    Out = header(CellPositionX, CellPositionY, CellType, NumClibs, NumIlibs, NumStatics, NumTriggers).

write_header(header(CellPositionX, CellPositionY, CellType, NumClibs, NumIlibs, NumStatics, NumTriggers), !IO) :-
    int_to_bytes(CellPositionX,CellPositionX0,CellPositionX1,CellPositionX2,CellPositionX3),
    io.write_byte(CellPositionX0, !IO),
    io.write_byte(CellPositionX1, !IO),
    io.write_byte(CellPositionX2, !IO),
    io.write_byte(CellPositionX3, !IO),
    int_to_bytes(CellPositionY,CellPositionY0,CellPositionY1,CellPositionY2,CellPositionY3),
    io.write_byte(CellPositionY0, !IO),
    io.write_byte(CellPositionY1, !IO),
    io.write_byte(CellPositionY2, !IO),
    io.write_byte(CellPositionY3, !IO),
    (
        CellType = interior, io.write_byte(0, !IO)
    ;
        CellType = exterior, io.write_byte(1, !IO)
    ),
    int_to_bytes(NumClibs,NumClibs0,NumClibs1,NumClibs2,NumClibs3),
    io.write_byte(NumClibs0, !IO),
    io.write_byte(NumClibs1, !IO),
    io.write_byte(NumClibs2, !IO),
    io.write_byte(NumClibs3, !IO),
    int_to_bytes(NumIlibs,NumIlibs0,NumIlibs1,NumIlibs2,NumIlibs3),
    io.write_byte(NumIlibs0, !IO),
    io.write_byte(NumIlibs1, !IO),
    io.write_byte(NumIlibs2, !IO),
    io.write_byte(NumIlibs3, !IO),
    int_to_bytes(NumStatics,NumStatics0,NumStatics1,NumStatics2,NumStatics3),
    io.write_byte(NumStatics0, !IO),
    io.write_byte(NumStatics1, !IO),
    io.write_byte(NumStatics2, !IO),
    io.write_byte(NumStatics3, !IO),
    int_to_bytes(NumTriggers,NumTriggers0,NumTriggers1,NumTriggers2,NumTriggers3),
    io.write_byte(NumTriggers0, !IO),
    io.write_byte(NumTriggers1, !IO),
    io.write_byte(NumTriggers2, !IO),
    io.write_byte(NumTriggers3, !IO),
    true.

read_trigger(Buffer, I0, IOut, Out) :- 
    get_8(Buffer, I0, TextSizeI0),
    get_ascii_string(Buffer, I0+1, TextSizeI0, Script),
    I1 - 1 = TextSizeI0 + I0,
    IOut = I1,
    Out = trigger(Script).

write_trigger(trigger(Script), !IO) :-
    string.length(Script) = 0+LenScript,
    io.write_byte(LenScript, !IO),
    write_string(Script, 0, LenScript, !IO),
    true.

read_static(Buffer, I0, IOut, Out) :- 
    read_position(Buffer, I0, I1, Location),
    get_8(Buffer, I1, TextSizeI1),
    get_ascii_string(Buffer, I1+1, TextSizeI1, Model),
    I2 - 1 = TextSizeI1 + I1,
    get_byte_float(Buffer, I2, RotX),
    I3 - 4 = I2,
    get_byte_float(Buffer, I3, RotY),
    I4 - 4 = I3,
    get_byte_float(Buffer, I4, RotZ),
    I5 - 4 = I4,
    IOut = I5,
    Out = static(Location, Model, RotX, RotY, RotZ).

write_static(static(Location, Model, RotX, RotY, RotZ), !IO) :-
    write_position(Location, !IO),
    string.length(Model) = 0+LenModel,
    io.write_byte(LenModel, !IO),
    write_string(Model, 0, LenModel, !IO),
    float_to_bytes(RotX,RotX0,RotX1,RotX2,RotX3),
    io.write_byte(RotX0, !IO),
    io.write_byte(RotX1, !IO),
    io.write_byte(RotX2, !IO),
    io.write_byte(RotX3, !IO),
    float_to_bytes(RotY,RotY0,RotY1,RotY2,RotY3),
    io.write_byte(RotY0, !IO),
    io.write_byte(RotY1, !IO),
    io.write_byte(RotY2, !IO),
    io.write_byte(RotY3, !IO),
    float_to_bytes(RotZ,RotZ0,RotZ1,RotZ2,RotZ3),
    io.write_byte(RotZ0, !IO),
    io.write_byte(RotZ1, !IO),
    io.write_byte(RotZ2, !IO),
    io.write_byte(RotZ3, !IO),
    true.

read_position(Buffer, I0, IOut, Out) :- 
    get_byte_float(Buffer, I0, X),
    I1 - 4 = I0,
    get_byte_float(Buffer, I1, Y),
    I2 - 4 = I1,
    get_byte_float(Buffer, I2, Z),
    I3 - 4 = I2,
    IOut = I3,
    Out = position(X, Y, Z).

write_position(position(X, Y, Z), !IO) :-
    float_to_bytes(X,X0,X1,X2,X3),
    io.write_byte(X0, !IO),
    io.write_byte(X1, !IO),
    io.write_byte(X2, !IO),
    io.write_byte(X3, !IO),
    float_to_bytes(Y,Y0,Y1,Y2,Y3),
    io.write_byte(Y0, !IO),
    io.write_byte(Y1, !IO),
    io.write_byte(Y2, !IO),
    io.write_byte(Y3, !IO),
    float_to_bytes(Z,Z0,Z1,Z2,Z3),
    io.write_byte(Z0, !IO),
    io.write_byte(Z1, !IO),
    io.write_byte(Z2, !IO),
    io.write_byte(Z3, !IO),
    true.


