// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "editor_ui.hpp"
#include "ilib_ui.h"
#include "cell_ui.h"
#include "clib_ui.h"
#include <FL/Fl_File_Chooser.H>
#include <FL/fl_ask.H>

CinEdit_EnumSystemUI CinEdit_GetActiveSystemUI() {
  const Fl_Widget *const active_tab = editor_tabs->value();
  if(active_tab == cell_tab)
      return eCinEdit_CellUI;
  else if(active_tab == item_tab)
      return eCinEdit_IlibUI;
  else // Error?
      return eCinEdit_CellUI;
}

void CinEdit_SetItemsExistUI() {
  item_delete_button->activate();
  item_info_frame->activate();
}

void CinEdit_SetItemsDoNotExistUI() {
  item_delete_button->deactivate();
  item_info_frame->deactivate();
}

void CinEdit_SetSaveActiveUI() {
  save_menu_item->activate();
  save_as_menu_item->activate();
}

void CinEdit_SetSaveInactiveUI() {
  save_menu_item->deactivate();
  save_as_menu_item->deactivate();
}

static void cb_Open(Fl_Menu_*, void*) {
  Fl_File_Chooser chooser("", "", Fl_File_Chooser::SINGLE, "");

const char *(*callback)(const char *) = NULL;

if(editor_tabs->value() == item_tab){
    chooser.filter("*.ilib");
    chooser.label("Open Item Library");
    callback = CinEdit_LoadItemLib;
}

chooser.show();
while(chooser.shown())
    Fl::wait();

if(chooser.count()){
    const char *const err = callback(chooser.value());
    if(err != NULL){
        fl_alert("Could not open file:\n%s", err);
    }
};
}

static void cb_save_menu_item(Fl_Menu_*, void*) {
  if(editor_tabs->value() == item_tab){
    CinEdit_SaveItemLib(CinEdit_GetItemLibraryPath());
};
}

static void cb_save_as_menu_item(Fl_Menu_*, void*) {
  Fl_File_Chooser chooser("", "", Fl_File_Chooser::CREATE, "");

const char *(*callback)(const char *) = NULL;

if(editor_tabs->value() == item_tab){
    chooser.filter("*.ilib");
    chooser.label("Save Item Library As...");
    callback = CinEdit_SaveItemLib;
}
else
    return;

chooser.show();
while(chooser.shown())
    Fl::wait();

if(chooser.count()){
    const char *const err = callback(chooser.value());
    if(err != NULL){
   //     fl_alert("Could not save file:\n%s", err);
    }
};
}

static void cb_undo_menu_item(Fl_Menu_*, void*) {
  const Fl_Widget *const selected_tab = editor_tabs->value();

if(selected_tab == item_tab){
    CinEdit_IlibUndo();
};
}

static void cb_redo_menu_item(Fl_Menu_*, void*) {
  const Fl_Widget *const selected_tab = editor_tabs->value();

if(selected_tab == item_tab){
    CinEdit_IlibRedo();
};
}

Fl_Menu_Item menu_[] = {
 {"&File", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&New", FL_COMMAND|0x6e,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Cr&eate", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"New &Cell", FL_COMMAND|0x10063,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"New &Item Lib", FL_COMMAND|0x10069,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Open", FL_COMMAND|0x6f,  (Fl_Callback*)cb_Open, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Save", FL_COMMAND|0x73,  (Fl_Callback*)cb_save_menu_item, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Save As", FL_COMMAND|0x10073,  (Fl_Callback*)cb_save_as_menu_item, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Export...", FL_COMMAND|0x10065,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Import...", FL_COMMAND|0x10069,  0, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Quit", FL_COMMAND|0x71,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Edit", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Undo", FL_COMMAND|0x7a,  (Fl_Callback*)cb_undo_menu_item, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Redo", FL_COMMAND|0x79,  (Fl_Callback*)cb_redo_menu_item, 0, 128, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"C&ut", FL_COMMAND|0x78,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Copy", FL_COMMAND|0x63,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Paste", FL_COMMAND|0x76,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Duplicate", FL_COMMAND|0x64,  0, 0, 128, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Find", FL_COMMAND|0x66,  0, 0, 128, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"&Preferences", FL_COMMAND|0x70,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Cell", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Interior", 0,  0, 0, 8, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Exterior", 0,  0, 0, 136, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Debug", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Dump Item Library", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Tabs *editor_tabs=(Fl_Tabs *)0;

static void cb_editor_tabs(Fl_Tabs* o, void*) {
  const Fl_Widget *const selected = static_cast<Fl_Tabs*>(o)->value();

if(selected == item_tab)
    CinEdit_IlibFocus();
else
    CinEdit_IlibUnfocus();
}

Fl_Group *cell_tab=(Fl_Group *)0;

Fl_Tabs *cell_tabs=(Fl_Tabs *)0;

static Fl_Group *heightmap_tab=(Fl_Group *)0;

static Fl_Group *statics_tab=(Fl_Group *)0;

Fl_Box *library_tile_resize_limiter=(Fl_Box *)0;

Fl_Group *item_tab=(Fl_Group *)0;

Fl_Browser *item_browser=(Fl_Browser *)0;

static void cb_item_browser(Fl_Browser*, void*) {
  CinEdit_RebuildItemInfoFrame2();
}

Fl_Group *item_info_frame=(Fl_Group *)0;

static Fl_Choice *item_type_choice=(Fl_Choice *)0;

static void cb_item_type_choice(Fl_Choice*, void* v) {
  if(const int v = item_browser->value()){
    const EnumItemTypeType item_type = 
        static_cast<EnumItemTypeType>(item_type_choice->value());
    CinEdit_SetItemType(v - 1, item_type);
};
}

Fl_Menu_Item menu_item_type_choice[] = {
 {"Armor", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Weapon", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Consumable", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Junk", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Wizard *item_type_wizard=(Fl_Wizard *)0;

Fl_Group *armor_wiz=(Fl_Group *)0;

static Fl_Choice *armor_type_choice=(Fl_Choice *)0;

Fl_Menu_Item menu_armor_type_choice[] = {
 {"Helmet", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Chestplate", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Boots", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Value_Input *armor_defense_input=(Fl_Value_Input *)0;

static Fl_Group *weapon_wiz=(Fl_Group *)0;

Fl_Choice *weapon_type_choice=(Fl_Choice *)0;

Fl_Menu_Item menu_weapon_type_choice[] = {
 {"Sword", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Axe", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Value_Input *weapon_attack_power_input=(Fl_Value_Input *)0;

Fl_Value_Input *weapon_attack_speed_input=(Fl_Value_Input *)0;

static Fl_Value_Input *item_value_input=(Fl_Value_Input *)0;

static void cb_item_value_input(Fl_Value_Input*, void* v) {
  if(const int v = item_browser->value())
    CinEdit_SetItemValue(v-1, item_value_input->value());
}

static Fl_Value_Input *item_durability_input=(Fl_Value_Input *)0;

static void cb_item_durability_input(Fl_Value_Input*, void* v) {
  if(const int v = item_browser->value())
    CinEdit_SetItemDurability(v-1, item_durability_input->value());
}

static Fl_Value_Input *item_weight_input=(Fl_Value_Input *)0;

static void cb_item_weight_input(Fl_Value_Input*, void* v) {
  if(const int v = item_browser->value())
    CinEdit_SetItemWeight(v-1, item_weight_input->value());
}

Fl_Input *item_name_input=(Fl_Input *)0;

static void cb_item_name_input(Fl_Input*, void*) {
  if(const int value = item_browser->value()){
    CinEdit_SetItemName(value - 1, item_name_input->value());
};
}

Fl_Box *item_icon_image_box=(Fl_Box *)0;

Fl_Input *item_model_input=(Fl_Input *)0;

static void cb_item_model_input(Fl_Input*, void* v) {
  if(const int v = item_browser->value()){
    if(!CinEdit_SetItemModel(v - 1, item_model_input->value())){
        item_model_input->color(FL_RED);
    }
    else{
        item_model_input->color(FL_WHITE);
    }
    item_browser->redraw();
};
}

Fl_Input *item_icon_input=(Fl_Input *)0;

static void cb_item_icon_input(Fl_Input*, void* v) {
  if(const int v = item_browser->value()){
    if(!CinEdit_SetItemIcon(v - 1, item_icon_input->value())){
        item_icon_input->color(FL_RED);
    }
    else{
        item_icon_input->color(FL_WHITE);
    }
};
}

static void cb_New(Fl_Button*, void*) {
  const char *const name = fl_input("Create New Item", "item");
if(name != NULL && *name)
    CinEdit_AddNewItemModel(name);
}

Fl_Button *item_delete_button=(Fl_Button *)0;

static void cb_item_delete_button(Fl_Button*, void*) {
  const int i = item_browser->value();
if(i > 0)
    CinEdit_RemoveItemModel(i - 1);
}

Fl_Double_Window* make_editor_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(680, 525, "Cinnabar Editor");
    w = o; if (w) {/* empty */}
    o->box(FL_THIN_UP_BOX);
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(-5, 0, 710, 25);
      o->selection_color((Fl_Color)133);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { editor_tabs = new Fl_Tabs(0, 25, 680, 505);
      editor_tabs->selection_color((Fl_Color)133);
      editor_tabs->callback((Fl_Callback*)cb_editor_tabs);
      editor_tabs->when(FL_WHEN_CHANGED);
      { cell_tab = new Fl_Group(0, 45, 680, 485, "Cell");
        cell_tab->selection_color((Fl_Color)133);
        cell_tab->hide();
        { cell_tabs = new Fl_Tabs(5, 50, 300, 470);
          cell_tabs->selection_color((Fl_Color)133);
          { heightmap_tab = new Fl_Group(5, 75, 300, 445, "Heightmap");
            heightmap_tab->hide();
            { Fl_File_Input* o = new Fl_File_Input(50, 81, 205, 34, "File:");
              o->selection_color((Fl_Color)133);
            } // Fl_File_Input* o
            { new Fl_Button(255, 90, 45, 25, "...");
            } // Fl_Button* o
            { new Fl_Box(50, 124, 205, 172, "Image...");
            } // Fl_Box* o
            heightmap_tab->end();
          } // Fl_Group* heightmap_tab
          { statics_tab = new Fl_Group(5, 75, 300, 445, "Statics");
            { Fl_Browser* o = new Fl_Browser(10, 95, 290, 395, "Statics");
              o->selection_color((Fl_Color)133);
              o->align(Fl_Align(FL_ALIGN_TOP));
            } // Fl_Browser* o
            { new Fl_Button(230, 495, 70, 20, "Add...");
            } // Fl_Button* o
            { new Fl_Button(155, 495, 70, 20, "Remove");
            } // Fl_Button* o
            { new Fl_Button(80, 495, 70, 20, "Clear");
            } // Fl_Button* o
            statics_tab->end();
          } // Fl_Group* statics_tab
          { Fl_Group* o = new Fl_Group(5, 75, 300, 445, "Triggers");
            o->hide();
            { Fl_Browser* o = new Fl_Browser(10, 95, 290, 395, "Triggers");
              o->selection_color((Fl_Color)133);
              o->align(Fl_Align(FL_ALIGN_TOP));
            } // Fl_Browser* o
            { new Fl_Button(230, 495, 70, 20, "Add...");
            } // Fl_Button* o
            { new Fl_Button(155, 495, 70, 20, "Remove");
            } // Fl_Button* o
            { new Fl_Button(80, 495, 70, 20, "Clear");
            } // Fl_Button* o
            o->end();
          } // Fl_Group* o
          { Fl_Group* o = new Fl_Group(5, 70, 300, 450, "Libraries");
            o->hide();
            { Fl_Tile* o = new Fl_Tile(5, 75, 300, 445);
              { library_tile_resize_limiter = new Fl_Box(24, 130, 35, 335);
                Fl_Group::current()->resizable(library_tile_resize_limiter);
              } // Fl_Box* library_tile_resize_limiter
              { Fl_Group* o = new Fl_Group(5, 75, 300, 230);
                o->box(FL_THIN_UP_BOX);
                { Fl_Browser* o = new Fl_Browser(10, 95, 290, 180, "Item Libraries");
                o->selection_color((Fl_Color)133);
                o->align(Fl_Align(FL_ALIGN_TOP));
                Fl_Group::current()->resizable(o);
                } // Fl_Browser* o
                { new Fl_Button(230, 280, 70, 20, "Add...");
                } // Fl_Button* o
                { new Fl_Button(155, 280, 70, 20, "Remove");
                } // Fl_Button* o
                { new Fl_Button(80, 280, 70, 20, "Clear");
                } // Fl_Button* o
                o->end();
              } // Fl_Group* o
              { Fl_Group* o = new Fl_Group(5, 305, 300, 215);
                o->box(FL_THIN_UP_BOX);
                { Fl_Browser* o = new Fl_Browser(10, 325, 290, 165, "Character Libraries");
                o->selection_color((Fl_Color)133);
                o->align(Fl_Align(FL_ALIGN_TOP));
                Fl_Group::current()->resizable(o);
                } // Fl_Browser* o
                { new Fl_Button(230, 495, 70, 20, "Add...");
                } // Fl_Button* o
                { new Fl_Button(80, 495, 70, 20, "Clear");
                } // Fl_Button* o
                { new Fl_Button(155, 495, 70, 20, "Remove");
                } // Fl_Button* o
                o->end();
              } // Fl_Group* o
              o->end();
            } // Fl_Tile* o
            o->end();
          } // Fl_Group* o
          cell_tabs->end();
        } // Fl_Tabs* cell_tabs
        cell_tab->end();
      } // Fl_Group* cell_tab
      { item_tab = new Fl_Group(0, 50, 680, 475, "Item Library");
        { Fl_Tile* o = new Fl_Tile(5, 55, 670, 465);
          { item_browser = new Fl_Browser(5, 55, 235, 465);
            item_browser->type(2);
            item_browser->selection_color((Fl_Color)133);
            item_browser->callback((Fl_Callback*)cb_item_browser);
            item_browser->when(FL_WHEN_CHANGED);
          } // Fl_Browser* item_browser
          { Fl_Group* o = new Fl_Group(240, 55, 435, 465);
            o->box(FL_FLAT_BOX);
            { item_info_frame = new Fl_Group(250, 60, 420, 420);
              item_info_frame->box(FL_ENGRAVED_BOX);
              item_info_frame->deactivate();
              { Fl_Box* o = new Fl_Box(505, 458, 160, 22);
                Fl_Group::current()->resizable(o);
              } // Fl_Box* o
              { item_type_choice = new Fl_Choice(300, 70, 115, 20, "Type");
                item_type_choice->down_box(FL_BORDER_BOX);
                item_type_choice->selection_color((Fl_Color)133);
                item_type_choice->callback((Fl_Callback*)cb_item_type_choice);
                item_type_choice->when(FL_WHEN_CHANGED);
                item_type_choice->menu(menu_item_type_choice);
              } // Fl_Choice* item_type_choice
              { item_type_wizard = new Fl_Wizard(260, 120, 400, 155);
                { armor_wiz = new Fl_Group(260, 120, 400, 155, "Armor");
                armor_wiz->box(FL_ENGRAVED_BOX);
                { armor_type_choice = new Fl_Choice(365, 130, 115, 20, "Armor Type");
                armor_type_choice->down_box(FL_BORDER_BOX);
                armor_type_choice->selection_color((Fl_Color)133);
                armor_type_choice->menu(menu_armor_type_choice);
                } // Fl_Choice* armor_type_choice
                { armor_defense_input = new Fl_Value_Input(365, 160, 115, 20, "Defense");
                armor_defense_input->selection_color((Fl_Color)133);
                armor_defense_input->maximum(4096);
                armor_defense_input->step(1);
                armor_defense_input->value(1);
                } // Fl_Value_Input* armor_defense_input
                armor_wiz->end();
                } // Fl_Group* armor_wiz
                { weapon_wiz = new Fl_Group(260, 120, 400, 155, "Weapon");
                weapon_wiz->box(FL_ENGRAVED_BOX);
                weapon_wiz->hide();
                { weapon_type_choice = new Fl_Choice(365, 130, 115, 20, "Weapon Type");
                weapon_type_choice->down_box(FL_BORDER_BOX);
                weapon_type_choice->selection_color((Fl_Color)133);
                weapon_type_choice->menu(menu_weapon_type_choice);
                } // Fl_Choice* weapon_type_choice
                { weapon_attack_power_input = new Fl_Value_Input(365, 160, 115, 20, "Attack Power");
                weapon_attack_power_input->selection_color((Fl_Color)133);
                weapon_attack_power_input->maximum(4096);
                weapon_attack_power_input->step(1);
                weapon_attack_power_input->value(1);
                } // Fl_Value_Input* weapon_attack_power_input
                { weapon_attack_speed_input = new Fl_Value_Input(365, 190, 115, 20, "Attack Speed");
                weapon_attack_speed_input->tooltip("milliseconds");
                weapon_attack_speed_input->selection_color((Fl_Color)133);
                weapon_attack_speed_input->maximum(4096);
                weapon_attack_speed_input->step(1);
                weapon_attack_speed_input->value(1);
                } // Fl_Value_Input* weapon_attack_speed_input
                { Fl_Box* o = new Fl_Box(490, 224, 160, 36);
                Fl_Group::current()->resizable(o);
                } // Fl_Box* o
                weapon_wiz->end();
                } // Fl_Group* weapon_wiz
                item_type_wizard->end();
              } // Fl_Wizard* item_type_wizard
              { item_value_input = new Fl_Value_Input(365, 282, 115, 20, "Value");
                item_value_input->selection_color((Fl_Color)133);
                item_value_input->callback((Fl_Callback*)cb_item_value_input);
              } // Fl_Value_Input* item_value_input
              { item_durability_input = new Fl_Value_Input(365, 310, 115, 20, "Durability");
                item_durability_input->selection_color((Fl_Color)133);
                item_durability_input->callback((Fl_Callback*)cb_item_durability_input);
              } // Fl_Value_Input* item_durability_input
              { item_weight_input = new Fl_Value_Input(365, 340, 115, 20, "Weight");
                item_weight_input->selection_color((Fl_Color)133);
                item_weight_input->callback((Fl_Callback*)cb_item_weight_input);
              } // Fl_Value_Input* item_weight_input
              { item_name_input = new Fl_Input(470, 70, 190, 20, "Name");
                item_name_input->callback((Fl_Callback*)cb_item_name_input);
              } // Fl_Input* item_name_input
              { item_icon_image_box = new Fl_Box(532, 282, 128, 128);
                item_icon_image_box->box(FL_THIN_UP_BOX);
                item_icon_image_box->color((Fl_Color)133);
                item_icon_image_box->selection_color((Fl_Color)133);
              } // Fl_Box* item_icon_image_box
              { new Fl_Button(480, 370, 35, 25, "...");
              } // Fl_Button* o
              { new Fl_Button(480, 405, 35, 25, "...");
              } // Fl_Button* o
              { item_model_input = new Fl_Input(350, 371, 130, 23, "Model");
                item_model_input->callback((Fl_Callback*)cb_item_model_input);
              } // Fl_Input* item_model_input
              { item_icon_input = new Fl_Input(350, 407, 130, 23, "Icon");
                item_icon_input->callback((Fl_Callback*)cb_item_icon_input);
              } // Fl_Input* item_icon_input
              item_info_frame->end();
              Fl_Group::current()->resizable(item_info_frame);
            } // Fl_Group* item_info_frame
            { Fl_Button* o = new Fl_Button(250, 490, 105, 25, "New");
              o->callback((Fl_Callback*)cb_New);
            } // Fl_Button* o
            { item_delete_button = new Fl_Button(365, 490, 105, 25, "Delete");
              item_delete_button->callback((Fl_Callback*)cb_item_delete_button);
              item_delete_button->deactivate();
            } // Fl_Button* item_delete_button
            o->end();
          } // Fl_Group* o
          o->end();
          Fl_Group::current()->resizable(o);
        } // Fl_Tile* o
        item_tab->end();
      } // Fl_Group* item_tab
      editor_tabs->end();
    } // Fl_Tabs* editor_tabs
    o->end();
  } // Fl_Double_Window* o
  return w;
}

void CinEdit_SetItemTypeArmor() {
  item_type_choice->value(armor_menu_item);
  item_type_wizard->value(armor_wiz);
}

void CinEdit_SetItemTypeWeapon() {
  item_type_choice->value(weapon_menu_item);
  item_type_wizard->value(weapon_wiz);
}

void CinEdit_SetItemTypeConsumable() {
  item_type_choice->value(consumable_menu_item);
  //item_type_wizard->value(armor_wiz);
}

void CinEdit_SetItemTypeJunk() {
  item_type_choice->value(junk_menu_item);
  //item_type_wizard->value(armor_wiz);
}

void CinEdit_SetItemAttributes(unsigned v, unsigned d, unsigned w, const char *icon, const char *model) {
  item_value_input->value(v);
  item_durability_input->value(d);
  item_weight_input->value(w);
  item_icon_input->value(icon);
  item_model_input->value(model);
}
