#pragma once
/* AUTOGENERATED, DO NOT EDIT
 * Created by libbottle generate.py, 2017-01-31
 */ 

#ifndef BOTTLE_ILIB_HEAD
#define BOTTLE_ILIB_HEAD

#include <stdio.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef BOTTLE_ENUMS
#define BOTTLE_ENUMS
#define BOTTLE_OK 0
#define BOTTLE_FAIL 1

struct BottleString { char *str; unsigned len; }; 
#endif

enum EnumBottleWeaponType{
    eSword,
    eAxe,
    NUM_WeaponType
};
enum EnumBottleItemType{
    eArmor,
    eWeapon,
    eConsumable,
    eJunk,
    NUM_ItemType
};
enum EnumBottleArmorType{
    eHelmet,
    eChestplate,
    eBoots,
    NUM_ArmorType
};
enum EnumBottleConsumableType{
    ePotion,
    NUM_ConsumableType
};
enum EnumBottleJunkType{
    eBook,
    eGem,
    NUM_JunkType
};
struct BottleItem;

unsigned Bottle_LoadItemMem(struct BottleItem *out, const void *mem, unsigned len);
unsigned Bottle_LoadItemFile(struct BottleItem *out, FILE *from);
void *Bottle_WriteItemMem(const struct BottleItem* from, unsigned *size_out);
void Bottle_WriteItemFile(const struct BottleItem* from, FILE *to);
struct BottleItem { 
    struct BottleString name;
    int weight;
    int durability;
    int value;
    struct BottleString model;
    struct BottleString icon;
    enum EnumBottleItemType ItemType;
    union{
        struct {
            int defense;
            enum EnumBottleArmorType atype;
        } armor;
        struct {
            enum EnumBottleWeaponType wtype;
            int speed;
            int attack;
        } weapon;
        struct {
            enum EnumBottleJunkType JunkType;
            union{
                struct {
                    struct BottleString text;
                } book;
                /* No members for gem*/
            }JunkTypeData;
        } junk;
        /* No members for consumable*/
    }ItemTypeData;
};

#ifdef __cplusplus
}
#endif

#endif
