:- module opengl2.
% AUTOGENERATED! DO NOT EDIT!
:- interface.
:- use_module opengl.
:- use_module io.
:- type matrix_mode --->modelview ; projection.
:- type light --->light0 ; light1 ; light2 ; light3 ; light4 ; light5 ; light6 ; light7.
:- type material --->ambient ; diffuse ; specular ; emission.
:- type face --->front ; back ; front_and_back.
:- pred light_position(light::in, float::in, float::in, float::in, float::in, Io::di, Io::uo) is det.
:- pred vertex(float::in, float::in, io.io::di, io.io::uo) is det.
:- pred pop_matrix(io.io::di, io.io::uo) is det.
:- pred tex_coord(float::in, float::in, io.io::di, io.io::uo) is det.
:- pred disable_texture(io.io::di, io.io::uo) is det.
:- pred draw_pixels(int::in, int::in, c_pointer::in, io.io::di, io.io::uo) is det.
:- pred begin(opengl.shape_type::in, io.io::di, io.io::uo) is det.
:- pred color(float::in, float::in, float::in, float::in, io.io::di, io.io::uo) is det.
:- pred enable_texture(io.io::di, io.io::uo) is det.
:- pred scale(float::in, float::in, float::in, io.io::di, io.io::uo) is det.
:- pred raster_pos(float::in, float::in, io.io::di, io.io::uo) is det.
:- pred rotate(float::in, float::in, float::in, float::in, io.io::di, io.io::uo) is det.
:- pred normal(float::in, float::in, float::in, io.io::di, io.io::uo) is det.
:- pred light(light::in, material::in, float::in, float::in, float::in, float::in, io.io::di, io.io::uo) is det.
:- pred translate(float::in, float::in, float::in, io.io::di, io.io::uo) is det.
:- pred color(float::in, float::in, float::in, io.io::di, io.io::uo) is det.
:- pred vertex(float::in, float::in, float::in, io.io::di, io.io::uo) is det.
:- pred load_identity(io.io::di, io.io::uo) is det.
:- pred frustum(float::in, float::in, float::in, float::in, float::in, float::in, io.io::di, io.io::uo) is det.
:- pred push_matrix(io.io::di, io.io::uo) is det.
:- pred matrix_mode(matrix_mode::in, io.io::di, io.io::uo) is det.
:- pred end(io.io::di, io.io::uo) is det.
:- pred ortho(float::in, float::in, float::in, float::in, float::in, float::in, io.io::di, io.io::uo) is det.
:- pred material(face::in, material::in, float::in, float::in, float::in, float::in, io.io::di, io.io::uo) is det.
:- implementation.
:- pragma foreign_decl("C", "#ifdef WIN32_
#include <Windows.h>
#include <GL/gl.h>
#endif").
:- pragma foreign_decl("C", "#ifdef __APPLE__
#include <OpenGL/gl.h>
#endif").
:- pragma foreign_decl("C", "#if (!(defined(__APPLE__))) && (!(defined(_WIN32)))
#include <GL/gl.h>
#endif").
:- pragma foreign_enum("C", matrix_mode/0, [modelview - "GL_MODELVIEW",projection - "GL_PROJECTION"]).
:- pragma foreign_enum("C", light/0, [light0 - "GL_LIGHT0",light1 - "GL_LIGHT1",light2 - "GL_LIGHT2",light3 - "GL_LIGHT3",light4 - "GL_LIGHT4",light5 - "GL_LIGHT5",light6 - "GL_LIGHT6",light7 - "GL_LIGHT7"]).
:- pragma foreign_enum("C", material/0, [ambient - "GL_AMBIENT",diffuse - "GL_DIFFUSE",specular - "GL_SPECULAR",emission - "GL_EMISSION"]).
:- pragma foreign_enum("C", face/0, [front - "GL_FRONT",back - "GL_BACK",front_and_back - "GL_FRONT_AND_BACK"]).
:- pragma foreign_proc("C", light_position(LIGHT0::in, FLOAT1::in, FLOAT2::in, FLOAT3::in, FLOAT4::in, IO5::di, IO6::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"float Array2[4];Array2[0] = FLOAT1;Array2[1] = FLOAT2;Array2[2] = FLOAT3;Array2[3] = FLOAT4;
	IO6=IO5;
glLightf(LIGHT0, GL_POSITION, Array2);").
:- pragma foreign_proc("C", vertex(FLOAT0::in, FLOAT1::in, IO2::di, IO3::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO3=IO2;
glVertex2f(FLOAT0, FLOAT1);").
:- pragma foreign_proc("C", pop_matrix(IO0::di, IO1::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO1=IO0;
glPopMatrix();").
:- pragma foreign_proc("C", tex_coord(FLOAT0::in, FLOAT1::in, IO2::di, IO3::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO3=IO2;
glTexCoord2f(FLOAT0, FLOAT1);").
:- pragma foreign_proc("C", disable_texture(IO0::di, IO1::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO1=IO0;
glDisable(GL_TEXTURE_2D);").
:- pragma foreign_proc("C", draw_pixels(INT0::in, INT1::in, C_POINTER2::in, IO3::di, IO4::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO4=IO3;
glDrawPixels(INT0, INT1, GL_RGBA, GL_UNSIGNED_BYTE, (const void*)C_POINTER2);").
:- pragma foreign_proc("C", begin(SHAPE_TYPE0::in, IO1::di, IO2::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO2=IO1;
glBegin(SHAPE_TYPE0);").
:- pragma foreign_proc("C", color(FLOAT0::in, FLOAT1::in, FLOAT2::in, FLOAT3::in, IO4::di, IO5::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO5=IO4;
glColor4f(FLOAT0, FLOAT1, FLOAT2, FLOAT3);").
:- pragma foreign_proc("C", enable_texture(IO0::di, IO1::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO1=IO0;
glEnable(GL_TEXTURE_2D);").
:- pragma foreign_proc("C", scale(FLOAT0::in, FLOAT1::in, FLOAT2::in, IO3::di, IO4::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO4=IO3;
glScalef(FLOAT0, FLOAT1, FLOAT2);").
:- pragma foreign_proc("C", raster_pos(FLOAT0::in, FLOAT1::in, IO2::di, IO3::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO3=IO2;
glRasterPos2f(FLOAT0, FLOAT1);").
:- pragma foreign_proc("C", rotate(FLOAT0::in, FLOAT1::in, FLOAT2::in, FLOAT3::in, IO4::di, IO5::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO5=IO4;
glRotatef(FLOAT0, FLOAT1, FLOAT2, FLOAT3);").
:- pragma foreign_proc("C", normal(FLOAT0::in, FLOAT1::in, FLOAT2::in, IO3::di, IO4::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO4=IO3;
glNormal3f(FLOAT0, FLOAT1, FLOAT2);").
:- pragma foreign_proc("C", light(LIGHT0::in, MATERIAL1::in, FLOAT2::in, FLOAT3::in, FLOAT4::in, FLOAT5::in, IO6::di, IO7::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"float Array2[4];Array2[0] = FLOAT2;Array2[1] = FLOAT3;Array2[2] = FLOAT4;Array2[3] = FLOAT5;
	IO7=IO6;
glLightf(LIGHT0, MATERIAL1, Array2);").
:- pragma foreign_proc("C", translate(FLOAT0::in, FLOAT1::in, FLOAT2::in, IO3::di, IO4::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO4=IO3;
glTranslatef(FLOAT0, FLOAT1, FLOAT2);").
:- pragma foreign_proc("C", color(FLOAT0::in, FLOAT1::in, FLOAT2::in, IO3::di, IO4::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO4=IO3;
glColor3f(FLOAT0, FLOAT1, FLOAT2);").
:- pragma foreign_proc("C", vertex(FLOAT0::in, FLOAT1::in, FLOAT2::in, IO3::di, IO4::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO4=IO3;
glVertex3f(FLOAT0, FLOAT1, FLOAT2);").
:- pragma foreign_proc("C", load_identity(IO0::di, IO1::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO1=IO0;
glLoadIdentity();").
:- pragma foreign_proc("C", frustum(FLOAT0::in, FLOAT1::in, FLOAT2::in, FLOAT3::in, FLOAT4::in, FLOAT5::in, IO6::di, IO7::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO7=IO6;
glFrustum(FLOAT0, FLOAT1, FLOAT2, FLOAT3, FLOAT4, FLOAT5);").
:- pragma foreign_proc("C", push_matrix(IO0::di, IO1::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO1=IO0;
glPushMatrix();").
:- pragma foreign_proc("C", matrix_mode(MATRIX_MODE0::in, IO1::di, IO2::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO2=IO1;
glMatrixMode(MATRIX_MODE0);").
:- pragma foreign_proc("C", end(IO0::di, IO1::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO1=IO0;
glEnd();").
:- pragma foreign_proc("C", ortho(FLOAT0::in, FLOAT1::in, FLOAT2::in, FLOAT3::in, FLOAT4::in, FLOAT5::in, IO6::di, IO7::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"	IO7=IO6;
glOrtho(FLOAT0, FLOAT1, FLOAT2, FLOAT3, FLOAT4, FLOAT5);").
:- pragma foreign_proc("C", material(FACE0::in, MATERIAL1::in, FLOAT2::in, FLOAT3::in, FLOAT4::in, FLOAT5::in, IO6::di, IO7::uo),[will_not_call_mercury, will_not_throw_exception,thread_safe, promise_pure, does_not_affect_liveness],"float Array2[4];Array2[0] = FLOAT2;Array2[1] = FLOAT3;Array2[2] = FLOAT4;Array2[3] = FLOAT5;
	IO7=IO6;
glMaterialfv(FACE0, MATERIAL1, Array2);").
